void uart_init(void);
void adc_init(void);
void controller_init(void);
void beep(unsigned int f_khz, unsigned int period_ms);
void beepSwipe(unsigned int f_khz1, unsigned int f_khz2, unsigned int period_ms);
unsigned char getProximity();
unsigned int read_adc(unsigned char adc_input);
void soundOK(void);
void soundQuestion(void);
void soundTick(void);
void soundCancel(void);
void soundAlarm(void);    
void soundPowerOverFlow(void);  
void soundPowerFailure(void);    
void soundBatteryLow(void);  
void lockMotorRoutine(void);   
void controllerReset(void); 
void bip(void);
unsigned char getIdFinally(unsigned char retries, unsigned char isForDoor);
void soundError(void);
void soundSuccess(void);  
void bips(unsigned char count);
